### ISSUE TITLE
Localhost is Not Valid IP

### ISSUE THREAD

**Issue by robmagary** [tunnckoCore/ip-filter#1]
This is not excepting the localhost IP of ::1

> verbose: Request IP is:  ::1
> verbose: Company IP array is:  [ '::1' ]
> verbose: CompanyAccess returned Error:  Error: ip-filter expect only valid IPv4/IPv6 IPs
>     at ipFilter (/Users/myaccount/Development/enterprise-app/node_modules/ip-filter/index.js:15:11)

Would there be any down side to supporting this?

**Comment by tunnckoCore** [comment]
The package doesn't do anything special, it just do 2 checks. This issue is [ip-regex](https://github.com/sindresorhus/ip-regex) related, sorry.
You can pass `strict:false` to make it works.

Cheers,
Charlike!
