### ISSUE TITLE
Security Issue ReDos

### ISSUE THREAD

**Issue by thiagobustamante** [tunnckoCore/ip-filter#8]
This package is using a dependency is-match@0.4.1 that is vulnerable to ReDos (regular expressions denial of service) attacks. Please, update this dependency to 1.0.0 to fix this problem.

For more informations, please check this:

https://snyk.io/test/npm/ip-filter/2.0.0?severity=high&severity=medium&severity=low

**Comment by thiagobustamante** [comment]
Can I send a Pull Request to fix it?

**Comment by tunnckoCore** [comment]
Yea yea! Definitely. Thanks.

**Comment by tunnckoCore** [comment]
Wow! How fast time pass... whole 8 months with v1 of `is-match`...

**Comment by tunnckoCore** [comment]
I'm only not sure about the breaking change behavior.

> prior to 1.0, when an array of globs was passed, isMatch() would return true if any of the globs matched. As of 1.0, isMatch() only returns true when all globs match.

But in any way, we should release major too.

**Comment by pdeveltere** [comment]
Would be great if `is-match` package could be updated to version 1.0.0!

**Comment by takahashi-jiec** [comment]
Please release a new version of the package.

npm audit

| Low | Regular Expression Denial of Service |
|---|---|
| Package | braces |
| Patched in | >=2.3.1 |
| Dependency of | ip-filter |
| Path | ip-filter > is-match > micromatch > braces  |
| More info | https://npmjs.com/advisories/786 |

**Comment by tunnckoCore** [comment]
I promise I'll do next release in 1-2 days.

**Comment by tunnckoCore** [comment]
Switched it to use micromatch v4, which is insanely faster, safer and accurate.

I'll publish, once the shitty slow TravisCI ends the build. Even it fails, it is 100% guaranteed that everything is working on Node.js >= 6/8 (I'm not sure for v6, was `const` supported there :thinking: ). 

I just didn't want to update everything (like scripts, ci, readme, @renovatebot activation and etc) in one go.

**Comment by tunnckoCore** [comment]
Ooops, so micromatch requires Node >= 8 :D  

So I will update everything: 
- bump major
- require node >= 8
- modernize codebase
- switch to circleci
- switch the license to MPL-2.0
- move to @tunnckoCoreHQ 
- activate full automation (e.g automatic dependency updates, and automated publishing) 

Sorry about that, but if don't want some of above bullets, then use the commit for installations. Because I can't publish v2.1 as I thought when it will require Node 8

**Comment by tunnckoCore** [comment]
Moved to the main monorepo where the stuff is happening nowadays. Soon v3 will be published to npm.

Find it here https://ghub.now.sh/ip-filter (or [tunnckoCore/opensource/ip-filter](https://github.com/tunnckoCore/opensource/tree/master/%40packages/ip-filter))
